name:                honeycomb
version:             0.1.0.0
github:              githubuser/honeycomb
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/EarnestResearch/libhoney-hs#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- aeson
- http-client
- http-client-tls
- http-types
- microlens
- microlens-mtl
- network-uri
- random
- stm
- uuid
- scientific
- wai
- resourcet
- conduit
- http-conduit

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  honeycomb-example-exe:
    main:                Main.hs
    source-dirs:         example
    dependencies:
    - honeycomb
    - http-types
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  honeycomb-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - honeycomb
    - hspec
    - transformers
    build-tools:
    - hspec-discover

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
