name: Test

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@releases/v7
    - uses: cachix/cachix-action@v4
      with:
        name: earnestresearch-oss
        signingKey: '${{ secrets.OSS_CACHIX_SIGNING_KEY }}'
        file: ci.nix
